// Mocks generated by Mockito 5.4.4 from annotations
// in azkari/test/data/repositories/adhkar_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:azkari/data/models/adhkar_model.dart' as _i6;
import 'package:azkari/data/models/daily_goal_model.dart' as _i7;
import 'package:azkari/data/models/tasbih_model.dart' as _i3;
import 'package:azkari/data/services/database_helper.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTasbihModel_1 extends _i1.SmartFake implements _i3.TasbihModel {
  _FakeTasbihModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i4.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Database> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i5.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.getter(#database),
        )),
      ) as _i5.Future<_i2.Database>);

  @override
  _i5.Future<List<_i6.AdhkarModel>> getAdhkarByCategory(String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAdhkarByCategory,
          [category],
        ),
        returnValue:
            _i5.Future<List<_i6.AdhkarModel>>.value(<_i6.AdhkarModel>[]),
      ) as _i5.Future<List<_i6.AdhkarModel>>);

  @override
  _i5.Future<List<String>> getCategories() => (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<List<_i6.AdhkarModel>> getAdhkarByIds(List<int>? ids) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAdhkarByIds,
          [ids],
        ),
        returnValue:
            _i5.Future<List<_i6.AdhkarModel>>.value(<_i6.AdhkarModel>[]),
      ) as _i5.Future<List<_i6.AdhkarModel>>);

  @override
  _i5.Future<List<_i3.TasbihModel>> getCustomTasbihList() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCustomTasbihList,
          [],
        ),
        returnValue:
            _i5.Future<List<_i3.TasbihModel>>.value(<_i3.TasbihModel>[]),
      ) as _i5.Future<List<_i3.TasbihModel>>);

  @override
  _i5.Future<_i3.TasbihModel> addTasbih(String? text) => (super.noSuchMethod(
        Invocation.method(
          #addTasbih,
          [text],
        ),
        returnValue: _i5.Future<_i3.TasbihModel>.value(_FakeTasbihModel_1(
          this,
          Invocation.method(
            #addTasbih,
            [text],
          ),
        )),
      ) as _i5.Future<_i3.TasbihModel>);

  @override
  _i5.Future<void> deleteTasbih(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTasbih,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setOrUpdateGoal(
    int? tasbihId,
    int? targetCount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setOrUpdateGoal,
          [
            tasbihId,
            targetCount,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeGoal(int? tasbihId) => (super.noSuchMethod(
        Invocation.method(
          #removeGoal,
          [tasbihId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> incrementGoalProgress(int? goalId) => (super.noSuchMethod(
        Invocation.method(
          #incrementGoalProgress,
          [goalId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i7.DailyGoalModel>> getGoalsWithTodayProgress() =>
      (super.noSuchMethod(
        Invocation.method(
          #getGoalsWithTodayProgress,
          [],
        ),
        returnValue:
            _i5.Future<List<_i7.DailyGoalModel>>.value(<_i7.DailyGoalModel>[]),
      ) as _i5.Future<List<_i7.DailyGoalModel>>);

  @override
  _i5.Future<Map<String, dynamic>?> getGoalForTasbih(int? tasbihId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGoalForTasbih,
          [tasbihId],
        ),
        returnValue: _i5.Future<Map<String, dynamic>?>.value(),
      ) as _i5.Future<Map<String, dynamic>?>);
}
